//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTravelExpert00.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents_Login
    {
        public int AgentId { get; set; }
        public string AgentPwd { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
