//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTravelExpert00.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpFirstName { get; set; }
        public string EmpMiddleInitial { get; set; }
        public string EmpLastName { get; set; }
        public string EmpBusPhone { get; set; }
        public string EmpEmail { get; set; }
        public string EmpPosition { get; set; }
    }
}
